# Generated by Django 5.2.5 on 2025-08-27 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'verbose_name': 'Кухар', 'verbose_name_plural': 'Кухарі'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='dishingredient',
            options={'verbose_name': 'Інгредієнт страви', 'verbose_name_plural': 'Інгредієнти страви'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'verbose_name': 'Тип страви', 'verbose_name_plural': 'Типи страв'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Інгредієнт', 'verbose_name_plural': 'Інгредієнти'},
        ),
        migrations.AddField(
            model_name='cook',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='cook',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.PositiveIntegerField(verbose_name='Роки досвіду'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooks',
            field=models.ManyToManyField(related_name='dishes', to='kitchen.cook', verbose_name='Кухарі'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.dishtype', verbose_name='Тип страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='dishes', through='kitchen.DishIngredient', to='kitchen.ingredient', verbose_name='Інгредієнти'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість на порцію'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.dish', verbose_name='Страва'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredient', verbose_name='Інгредієнт'),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип страви'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва інгредієнта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Запас'),
        ),
    ]
