# Generated by Django 5.2.5 on 2025-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_cook_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cooks_photos/',
                                    verbose_name='Фото'
                                    ),
        ),
    ]
